alias c=cd
alias d=docker
alias dc=docker-compose
alias dcb="docker-compose build"
alias dcd="docker-compose down"
alias dce="docker-compose exec"
alias dcu="docker-compose up"
alias g=git
alias ga="git add"
alias gb="git branch"
alias gc="git commit -v"
alias gca="git commit -v --amend"
alias gco="git checkout"
alias gd="git diff"
alias gf="git fetch"
alias gg="git grep"
alias gl="git pull"
alias gm="git merge"
alias gp="git push"
alias gs="git status"
alias j=jobs
alias k=kubectl
alias l=ls
alias la="ls -a"
alias ls="ls --color=auto -F"
alias m=make
alias md="mkdir -p"
alias rm="rm -f"
alias t=tree
alias tf=terraform
alias tm=tmux
alias v=vim
